---

- name: Perform apt-get update
  apt:
    update_cache: yes

- name: Perform apt-get upgrade
  apt:
    upgrade: full

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer requred.
  apt:
    autoremove: yes
