---

- name: Create GENERAL_NETWORK for project
  os_network:
    state: present
    name: GENERAL_NETWORK
    project: "{{ TEST_PROJECT_NAME }}"
  register: gen_net_result

- debug:
    msg: "General network result: {{ gen_net_result }}"

- name: Create subnet on GENERAL_NETWORK
  os_subnet:
    state: present
    network_name: GENERAL_NETWORK
    name: gen1subnet1
    cidr: 172.24.220.0/24
    project: "{{ TEST_PROJECT_NAME }}"
  register: gen_subnet1_result

- debug:
    msg: "Subnet results: {{ gen_subnet1_result }}"

- name: Gather network info
  os_networks_facts:
  register: net_facts

- debug:
    msg: "Network facts: {{ item['router:external'] }}"
  with_items: "{{ net_facts.ansible_facts.openstack_networks }}"

- set_fact:
    ext_net: "{{ item.name }}"
  with_items: "{{ net_facts.ansible_facts.openstack_networks }}"
  when: "{{ item['router:external'] }}"

- debug:
    msg: "External network: {{ ext_net }}"

- name: Create router for test project
  os_router:
    state: present
    name: GENERAL_ROUTER
    project: "{{ TEST_PROJECT_NAME }}"
    network: "{{ ext_net }}"
    interfaces:
      - gen1subnet1
  register: rtr_results

- debug:
    msg: "Router results: {{ rtr_results }}"