---
    # Create a project
  - name: Creating Test Project
    os_project:
      endpoint_type: admin
      state: present
      name: "{{ TEST_PROJECT_NAME }}"
      description: "{{ TEST_PROJECT_DESCRIPTION }}"
      domain_id: "{{ TEST_PROJECT_DOMAIN_ID }}"
      enabled: True
    register: test_project

  - debug:
      msg: "Test Project Name: {{ test_project.project.name }}, ID: {{ test_project.project.id }}"