---

    # Create a project
  - os_project:
      endpoint_type: admin
      state: present
      name: "{{ PROJECT_NAME }}"
      description: "{{ PROJECT_DESCRIPTION }}"
      domain_id: "{{ PROJECT_DOMAIN_ID }}"
      enabled: True
    register: test_project

  - debug:
      msg: "Test Project Name: {{ test_project.project.name }}, ID: {{ test_project.project.id }}"